[package]
name = "egui_json_tree"
version = "0.1.0"
authors = ["Duncan MacKinnon <dmackdev@gmail.com>"]
edition = "2021"
description = "A JSON tree visualiser widget for egui."
repository = "https://github.com/dmackdev/egui_json_tree"
license = "MIT"

[dependencies]
egui = "0.22.0"
serde_json = "1.0.104"

[dev-dependencies]
eframe = "0.22.0"
