[package]
name = "egui_json_tree"
version = "0.1.0"
authors = ["Duncan MacKinnon <dmackdev@gmail.com>"]
edition = "2021"
description = "An interactive JSON tree visualisation library for egui, with search and highlight functionality."
repository = "https://github.com/dmackdev/egui_json_tree"
license = "MIT"

[dependencies]
egui = { git = "https://github.com/emilk/egui", rev = "481f448" }
serde_json = { version = "1.0.104", optional = true }

[dev-dependencies]
eframe = { git = "https://github.com/emilk/egui", rev = "481f448" }

[features]
default = ["serde_json"]
serde_json = ["dep:serde_json"]
