name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
      - name: Format
        run: cargo fmt --all -- --check
      - name: Docs
        run: cargo doc --lib --no-deps --all-features
      - name: Clippy
        run: cargo clippy --workspace
      - name: Build
        run: cargo build --locked --workspace

  check-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
      - name: Cargo check
        run: cargo check --locked --all-targets --all-features --workspace

  test:
    needs: build
    runs-on: macos-15 # For snapshot testing.
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
      - name: Test
        run: cargo test --locked --workspace
      - name: Test for simd_json feature
        run: cargo test --locked --package egui_json_tree --test image_snapshot_tests --features simd_json --no-default-features

  web-demo:
    needs: test
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
      - uses: jetli/trunk-action@1346cc09eace4beb84e403e199a471346d4684c9 # v0.5.1
        with:
          version: "v0.21.14"
      - name: Trunk build
        working-directory: demo
        run: trunk build --locked --release --public-url /egui_json_tree
      - name: Maybe deploy web demo
        if: github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@df5cc2bfa78282ded844b354faee141f06b41865 # v4.2.0
        with:
          build_dir: demo/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
