name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
      - name: Test json_tree_test for simd_json feature
        run: cargo test --features=simd_json --no-default-features --test json_tree_test
      - name: Clippy
        run: cargo clippy
      - name: Format
        run: cargo fmt --all -- --check

  web-demo:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: jetli/trunk-action@v0.5.0
        with:
          version: "v0.20.3"
      - name: Trunk build
        working-directory: examples/demo
        run: trunk build --release --public-url /egui_json_tree
      - name: Maybe deploy web demo
        if: github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: examples/demo/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
